name: Check version

on:
  push:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  check_node_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check synchronize volta and .node_version
        uses: My-MC/check-sync-volta-and-node-version@v0.0.2
